// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.javacoding.xsearch.cluster.protocol;

public final class Cluster {
  private Cluster() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\rcluster.proto\022\'net.javacoding.xsearch." +
      "cluster.protocol\"\246\004\n\016ClusterMessage\022\030\n\020s" +
      "erver_unique_id\030\001 \002(\003\022\026\n\016is_index_ready\030" +
      "\002 \001(\010\022H\n\013index_ready\030\003 \001(\01323.net.javacod" +
      "ing.xsearch.cluster.protocol.IndexReady\022" +
      "\027\n\017is_list_request\030\004 \001(\010\022J\n\014list_request" +
      "\030\005 \001(\01324.net.javacoding.xsearch.cluster." +
      "protocol.ListRequest\022\030\n\020is_list_response" +
      "\030\006 \001(\010\022L\n\rlist_response\030\007 \001(\01325.net.java" +
      "coding.xsearch.cluster.protocol.ListResp" +
      "onse\022\027\n\017is_ping_request\030\010 \001(\010\022J\n\014ping_re" +
      "quest\030\t \001(\01324.net.javacoding.xsearch.clu" +
      "ster.protocol.PingRequest\022\030\n\020is_ping_res" +
      "ponse\030\n \001(\010\022L\n\rping_response\030\013 \001(\01325.net" +
      ".javacoding.xsearch.cluster.protocol.Pin" +
      "gResponse\"K\n\nIndexReady\022\r\n\005index\030\001 \002(\t\022\026" +
      "\n\016main_timestamp\030\002 \002(\003\022\026\n\016temp_timestamp" +
      "\030\003 \001(\003\"\r\n\013ListRequest\"\230\001\n\014ListResponse\022W" +
      "\n\014index_status\030\001 \003(\0132A.net.javacoding.xs" +
      "earch.cluster.protocol.ListResponse.Inde" +
      "xStatus\032/\n\013IndexStatus\022\r\n\005index\030\001 \002(\t\022\021\n" +
      "\ttimestamp\030\002 \002(\003\"\r\n\013PingRequest\"}\n\014PingR" +
      "esponse\022\022\n\nip_address\030\001 \002(\t\022\021\n\thost_name" +
      "\030\002 \002(\t\022\023\n\013port_number\030\003 \002(\003\022\033\n\023licensed_" +
      "ip_or_host\030\004 \002(\t\022\024\n\014license_user\030\005 \001(\tB2" +
      "\n\'net.javacoding.xsearch.cluster.protoco" +
      "lB\007Cluster";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"cluster.proto\".", e);
    }
  }
  
  public static final class ClusterMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use ClusterMessage.newBuilder() to construct.
    private ClusterMessage() {}
    
    private static final ClusterMessage defaultInstance = new ClusterMessage();
    public static ClusterMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClusterMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ClusterMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ClusterMessage_fieldAccessorTable;
    }
    
    // required int64 server_unique_id = 1;
    private boolean hasServerUniqueId;
    private long serverUniqueId_ = 0L;
    public boolean hasServerUniqueId() { return hasServerUniqueId; }
    public long getServerUniqueId() { return serverUniqueId_; }
    
    // optional bool is_index_ready = 2;
    private boolean hasIsIndexReady;
    private boolean isIndexReady_ = false;
    public boolean hasIsIndexReady() { return hasIsIndexReady; }
    public boolean getIsIndexReady() { return isIndexReady_; }
    
    // optional .net.javacoding.xsearch.cluster.protocol.IndexReady index_ready = 3;
    private boolean hasIndexReady;
    private net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady indexReady_ = net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.getDefaultInstance();
    public boolean hasIndexReady() { return hasIndexReady; }
    public net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady getIndexReady() { return indexReady_; }
    
    // optional bool is_list_request = 4;
    private boolean hasIsListRequest;
    private boolean isListRequest_ = false;
    public boolean hasIsListRequest() { return hasIsListRequest; }
    public boolean getIsListRequest() { return isListRequest_; }
    
    // optional .net.javacoding.xsearch.cluster.protocol.ListRequest list_request = 5;
    private boolean hasListRequest;
    private net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest listRequest_ = net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.getDefaultInstance();
    public boolean hasListRequest() { return hasListRequest; }
    public net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest getListRequest() { return listRequest_; }
    
    // optional bool is_list_response = 6;
    private boolean hasIsListResponse;
    private boolean isListResponse_ = false;
    public boolean hasIsListResponse() { return hasIsListResponse; }
    public boolean getIsListResponse() { return isListResponse_; }
    
    // optional .net.javacoding.xsearch.cluster.protocol.ListResponse list_response = 7;
    private boolean hasListResponse;
    private net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse listResponse_ = net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.getDefaultInstance();
    public boolean hasListResponse() { return hasListResponse; }
    public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse getListResponse() { return listResponse_; }
    
    // optional bool is_ping_request = 8;
    private boolean hasIsPingRequest;
    private boolean isPingRequest_ = false;
    public boolean hasIsPingRequest() { return hasIsPingRequest; }
    public boolean getIsPingRequest() { return isPingRequest_; }
    
    // optional .net.javacoding.xsearch.cluster.protocol.PingRequest ping_request = 9;
    private boolean hasPingRequest;
    private net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest pingRequest_ = net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.getDefaultInstance();
    public boolean hasPingRequest() { return hasPingRequest; }
    public net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest getPingRequest() { return pingRequest_; }
    
    // optional bool is_ping_response = 10;
    private boolean hasIsPingResponse;
    private boolean isPingResponse_ = false;
    public boolean hasIsPingResponse() { return hasIsPingResponse; }
    public boolean getIsPingResponse() { return isPingResponse_; }
    
    // optional .net.javacoding.xsearch.cluster.protocol.PingResponse ping_response = 11;
    private boolean hasPingResponse;
    private net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse pingResponse_ = net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.getDefaultInstance();
    public boolean hasPingResponse() { return hasPingResponse; }
    public net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse getPingResponse() { return pingResponse_; }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage result = new net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage buildPartial() {
        net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required int64 server_unique_id = 1;
      public boolean hasServerUniqueId() {
        return result.hasServerUniqueId();
      }
      public long getServerUniqueId() {
        return result.getServerUniqueId();
      }
      public Builder setServerUniqueId(long value) {
        result.hasServerUniqueId = true;
        result.serverUniqueId_ = value;
        return this;
      }
      public Builder clearServerUniqueId() {
        result.hasServerUniqueId = false;
        result.serverUniqueId_ = 0L;
        return this;
      }
      
      // optional bool is_index_ready = 2;
      public boolean hasIsIndexReady() {
        return result.hasIsIndexReady();
      }
      public boolean getIsIndexReady() {
        return result.getIsIndexReady();
      }
      public Builder setIsIndexReady(boolean value) {
        result.hasIsIndexReady = true;
        result.isIndexReady_ = value;
        return this;
      }
      public Builder clearIsIndexReady() {
        result.hasIsIndexReady = false;
        result.isIndexReady_ = false;
        return this;
      }
      
      // optional .net.javacoding.xsearch.cluster.protocol.IndexReady index_ready = 3;
      public boolean hasIndexReady() {
        return result.hasIndexReady();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady getIndexReady() {
        return result.getIndexReady();
      }
      public Builder setIndexReady(net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady value) {
        result.hasIndexReady = true;
        result.indexReady_ = value;
        return this;
      }
      public Builder setIndexReady(net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.Builder builderForValue) {
        result.hasIndexReady = true;
        result.indexReady_ = builderForValue.build();
        return this;
      }
      public Builder mergeIndexReady(net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady value) {
        if (result.hasIndexReady() &&
            result.indexReady_ != net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.getDefaultInstance()) {
          result.indexReady_ =
            net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.newBuilder(result.indexReady_).mergeFrom(value).buildPartial();
        } else {
          result.indexReady_ = value;
        }
        result.hasIndexReady = true;
        return this;
      }
      public Builder clearIndexReady() {
        result.hasIndexReady = false;
        result.indexReady_ = net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.getDefaultInstance();
        return this;
      }
      
      // optional bool is_list_request = 4;
      public boolean hasIsListRequest() {
        return result.hasIsListRequest();
      }
      public boolean getIsListRequest() {
        return result.getIsListRequest();
      }
      public Builder setIsListRequest(boolean value) {
        result.hasIsListRequest = true;
        result.isListRequest_ = value;
        return this;
      }
      public Builder clearIsListRequest() {
        result.hasIsListRequest = false;
        result.isListRequest_ = false;
        return this;
      }
      
      // optional .net.javacoding.xsearch.cluster.protocol.ListRequest list_request = 5;
      public boolean hasListRequest() {
        return result.hasListRequest();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest getListRequest() {
        return result.getListRequest();
      }
      public Builder setListRequest(net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest value) {
        result.hasListRequest = true;
        result.listRequest_ = value;
        return this;
      }
      public Builder setListRequest(net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.Builder builderForValue) {
        result.hasListRequest = true;
        result.listRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeListRequest(net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest value) {
        if (result.hasListRequest() &&
            result.listRequest_ != net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.getDefaultInstance()) {
          result.listRequest_ =
            net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.newBuilder(result.listRequest_).mergeFrom(value).buildPartial();
        } else {
          result.listRequest_ = value;
        }
        result.hasListRequest = true;
        return this;
      }
      public Builder clearListRequest() {
        result.hasListRequest = false;
        result.listRequest_ = net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.getDefaultInstance();
        return this;
      }
      
      // optional bool is_list_response = 6;
      public boolean hasIsListResponse() {
        return result.hasIsListResponse();
      }
      public boolean getIsListResponse() {
        return result.getIsListResponse();
      }
      public Builder setIsListResponse(boolean value) {
        result.hasIsListResponse = true;
        result.isListResponse_ = value;
        return this;
      }
      public Builder clearIsListResponse() {
        result.hasIsListResponse = false;
        result.isListResponse_ = false;
        return this;
      }
      
      // optional .net.javacoding.xsearch.cluster.protocol.ListResponse list_response = 7;
      public boolean hasListResponse() {
        return result.hasListResponse();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse getListResponse() {
        return result.getListResponse();
      }
      public Builder setListResponse(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse value) {
        result.hasListResponse = true;
        result.listResponse_ = value;
        return this;
      }
      public Builder setListResponse(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.Builder builderForValue) {
        result.hasListResponse = true;
        result.listResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeListResponse(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse value) {
        if (result.hasListResponse() &&
            result.listResponse_ != net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.getDefaultInstance()) {
          result.listResponse_ =
            net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.newBuilder(result.listResponse_).mergeFrom(value).buildPartial();
        } else {
          result.listResponse_ = value;
        }
        result.hasListResponse = true;
        return this;
      }
      public Builder clearListResponse() {
        result.hasListResponse = false;
        result.listResponse_ = net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.getDefaultInstance();
        return this;
      }
      
      // optional bool is_ping_request = 8;
      public boolean hasIsPingRequest() {
        return result.hasIsPingRequest();
      }
      public boolean getIsPingRequest() {
        return result.getIsPingRequest();
      }
      public Builder setIsPingRequest(boolean value) {
        result.hasIsPingRequest = true;
        result.isPingRequest_ = value;
        return this;
      }
      public Builder clearIsPingRequest() {
        result.hasIsPingRequest = false;
        result.isPingRequest_ = false;
        return this;
      }
      
      // optional .net.javacoding.xsearch.cluster.protocol.PingRequest ping_request = 9;
      public boolean hasPingRequest() {
        return result.hasPingRequest();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest getPingRequest() {
        return result.getPingRequest();
      }
      public Builder setPingRequest(net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest value) {
        result.hasPingRequest = true;
        result.pingRequest_ = value;
        return this;
      }
      public Builder setPingRequest(net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.Builder builderForValue) {
        result.hasPingRequest = true;
        result.pingRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePingRequest(net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest value) {
        if (result.hasPingRequest() &&
            result.pingRequest_ != net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.getDefaultInstance()) {
          result.pingRequest_ =
            net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.newBuilder(result.pingRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pingRequest_ = value;
        }
        result.hasPingRequest = true;
        return this;
      }
      public Builder clearPingRequest() {
        result.hasPingRequest = false;
        result.pingRequest_ = net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.getDefaultInstance();
        return this;
      }
      
      // optional bool is_ping_response = 10;
      public boolean hasIsPingResponse() {
        return result.hasIsPingResponse();
      }
      public boolean getIsPingResponse() {
        return result.getIsPingResponse();
      }
      public Builder setIsPingResponse(boolean value) {
        result.hasIsPingResponse = true;
        result.isPingResponse_ = value;
        return this;
      }
      public Builder clearIsPingResponse() {
        result.hasIsPingResponse = false;
        result.isPingResponse_ = false;
        return this;
      }
      
      // optional .net.javacoding.xsearch.cluster.protocol.PingResponse ping_response = 11;
      public boolean hasPingResponse() {
        return result.hasPingResponse();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse getPingResponse() {
        return result.getPingResponse();
      }
      public Builder setPingResponse(net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse value) {
        result.hasPingResponse = true;
        result.pingResponse_ = value;
        return this;
      }
      public Builder setPingResponse(net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.Builder builderForValue) {
        result.hasPingResponse = true;
        result.pingResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergePingResponse(net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse value) {
        if (result.hasPingResponse() &&
            result.pingResponse_ != net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.getDefaultInstance()) {
          result.pingResponse_ =
            net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.newBuilder(result.pingResponse_).mergeFrom(value).buildPartial();
        } else {
          result.pingResponse_ = value;
        }
        result.hasPingResponse = true;
        return this;
      }
      public Builder clearPingResponse() {
        result.hasPingResponse = false;
        result.pingResponse_ = net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.getDefaultInstance();
        return this;
      }
    }
  }
  
  public static final class IndexReady extends
      com.google.protobuf.GeneratedMessage {
    // Use IndexReady.newBuilder() to construct.
    private IndexReady() {}
    
    private static final IndexReady defaultInstance = new IndexReady();
    public static IndexReady getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexReady getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_IndexReady_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_IndexReady_fieldAccessorTable;
    }
    
    // required string index = 1;
    private boolean hasIndex;
    private java.lang.String index_ = "";
    public boolean hasIndex() { return hasIndex; }
    public java.lang.String getIndex() { return index_; }
    
    // required int64 main_timestamp = 2;
    private boolean hasMainTimestamp;
    private long mainTimestamp_ = 0L;
    public boolean hasMainTimestamp() { return hasMainTimestamp; }
    public long getMainTimestamp() { return mainTimestamp_; }
    
    // optional int64 temp_timestamp = 3;
    private boolean hasTempTimestamp;
    private long tempTimestamp_ = 0L;
    public boolean hasTempTimestamp() { return hasTempTimestamp; }
    public long getTempTimestamp() { return tempTimestamp_; }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady result = new net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady buildPartial() {
        net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string index = 1;
      public boolean hasIndex() {
        return result.hasIndex();
      }
      public java.lang.String getIndex() {
        return result.getIndex();
      }
      public Builder setIndex(java.lang.String value) {
        result.hasIndex = true;
        result.index_ = value;
        return this;
      }
      public Builder clearIndex() {
        result.hasIndex = false;
        result.index_ = "";
        return this;
      }
      
      // required int64 main_timestamp = 2;
      public boolean hasMainTimestamp() {
        return result.hasMainTimestamp();
      }
      public long getMainTimestamp() {
        return result.getMainTimestamp();
      }
      public Builder setMainTimestamp(long value) {
        result.hasMainTimestamp = true;
        result.mainTimestamp_ = value;
        return this;
      }
      public Builder clearMainTimestamp() {
        result.hasMainTimestamp = false;
        result.mainTimestamp_ = 0L;
        return this;
      }
      
      // optional int64 temp_timestamp = 3;
      public boolean hasTempTimestamp() {
        return result.hasTempTimestamp();
      }
      public long getTempTimestamp() {
        return result.getTempTimestamp();
      }
      public Builder setTempTimestamp(long value) {
        result.hasTempTimestamp = true;
        result.tempTimestamp_ = value;
        return this;
      }
      public Builder clearTempTimestamp() {
        result.hasTempTimestamp = false;
        result.tempTimestamp_ = 0L;
        return this;
      }
    }
  }
  
  public static final class ListRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ListRequest.newBuilder() to construct.
    private ListRequest() {}
    
    private static final ListRequest defaultInstance = new ListRequest();
    public static ListRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListRequest_fieldAccessorTable;
    }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest buildPartial() {
        net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
    }
  }
  
  public static final class ListResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ListResponse.newBuilder() to construct.
    private ListResponse() {}
    
    private static final ListResponse defaultInstance = new ListResponse();
    public static ListResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_fieldAccessorTable;
    }
    
    public static final class IndexStatus extends
        com.google.protobuf.GeneratedMessage {
      // Use IndexStatus.newBuilder() to construct.
      private IndexStatus() {}
      
      private static final IndexStatus defaultInstance = new IndexStatus();
      public static IndexStatus getDefaultInstance() {
        return defaultInstance;
      }
      
      public IndexStatus getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_IndexStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_IndexStatus_fieldAccessorTable;
      }
      
      // required string index = 1;
      private boolean hasIndex;
      private java.lang.String index_ = "";
      public boolean hasIndex() { return hasIndex; }
      public java.lang.String getIndex() { return index_; }
      
      // required int64 timestamp = 2;
      private boolean hasTimestamp;
      private long timestamp_ = 0L;
      public boolean hasTimestamp() { return hasTimestamp; }
      public long getTimestamp() { return timestamp_; }
      
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return new Builder(); }
      public Builder newBuilderForType() { return new Builder(); }
      public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus prototype) {
        return new Builder().mergeFrom(prototype);
      }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.newBuilder()
        private Builder() {}
        
        net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus();
        
        protected net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus();
          return this;
        }
        
        public Builder clone() {
          return new Builder().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.getDescriptor();
        }
        
        public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus getDefaultInstanceForType() {
          return net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.getDefaultInstance();
        }
        
        public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus build() {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result);
          }
          return buildPartial();
        }
        
        private net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus buildPartial() {
          net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus returnMe = result;
          result = null;
          return returnMe;
        }
        
        
        // required string index = 1;
        public boolean hasIndex() {
          return result.hasIndex();
        }
        public java.lang.String getIndex() {
          return result.getIndex();
        }
        public Builder setIndex(java.lang.String value) {
          result.hasIndex = true;
          result.index_ = value;
          return this;
        }
        public Builder clearIndex() {
          result.hasIndex = false;
          result.index_ = "";
          return this;
        }
        
        // required int64 timestamp = 2;
        public boolean hasTimestamp() {
          return result.hasTimestamp();
        }
        public long getTimestamp() {
          return result.getTimestamp();
        }
        public Builder setTimestamp(long value) {
          result.hasTimestamp = true;
          result.timestamp_ = value;
          return this;
        }
        public Builder clearTimestamp() {
          result.hasTimestamp = false;
          result.timestamp_ = 0L;
          return this;
        }
      }
    }
    
    // repeated .net.javacoding.xsearch.cluster.protocol.ListResponse.IndexStatus index_status = 1;
    private java.util.List<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus> indexStatus_ =
      java.util.Collections.emptyList();
    public java.util.List<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus> getIndexStatusList() {
      return indexStatus_;
    }
    public int getIndexStatusCount() { return indexStatus_.size(); }
    public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus getIndexStatus(int index) {
      return indexStatus_.get(index);
    }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse buildPartial() {
        if (result.indexStatus_ != java.util.Collections.EMPTY_LIST) {
          result.indexStatus_ =
            java.util.Collections.unmodifiableList(result.indexStatus_);
        }
        net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .net.javacoding.xsearch.cluster.protocol.ListResponse.IndexStatus index_status = 1;
      public java.util.List<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus> getIndexStatusList() {
        return java.util.Collections.unmodifiableList(result.indexStatus_);
      }
      public int getIndexStatusCount() {
        return result.getIndexStatusCount();
      }
      public net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus getIndexStatus(int index) {
        return result.getIndexStatus(index);
      }
      public Builder setIndexStatus(int index, net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus value) {
        result.indexStatus_.set(index, value);
        return this;
      }
      public Builder setIndexStatus(int index, net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.Builder builderForValue) {
        result.indexStatus_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIndexStatus(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus value) {
        if (result.indexStatus_.isEmpty()) {
          result.indexStatus_ = new java.util.ArrayList<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus>();
        }
        result.indexStatus_.add(value);
        return this;
      }
      public Builder addIndexStatus(net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.Builder builderForValue) {
        if (result.indexStatus_.isEmpty()) {
          result.indexStatus_ = new java.util.ArrayList<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus>();
        }
        result.indexStatus_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIndexStatus(
          java.lang.Iterable<? extends net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus> values) {
        if (result.indexStatus_.isEmpty()) {
          result.indexStatus_ = new java.util.ArrayList<net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus>();
        }
        super.addAll(values, result.indexStatus_);
        return this;
      }
      public Builder clearIndexStatus() {
        result.indexStatus_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class PingRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use PingRequest.newBuilder() to construct.
    private PingRequest() {}
    
    private static final PingRequest defaultInstance = new PingRequest();
    public static PingRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public PingRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_PingRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_PingRequest_fieldAccessorTable;
    }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest result = new net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest buildPartial() {
        net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
    }
  }
  
  public static final class PingResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use PingResponse.newBuilder() to construct.
    private PingResponse() {}
    
    private static final PingResponse defaultInstance = new PingResponse();
    public static PingResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public PingResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_PingResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.javacoding.xsearch.cluster.protocol.Cluster.internal_static_net_javacoding_xsearch_cluster_protocol_PingResponse_fieldAccessorTable;
    }
    
    // required string ip_address = 1;
    private boolean hasIpAddress;
    private java.lang.String ipAddress_ = "";
    public boolean hasIpAddress() { return hasIpAddress; }
    public java.lang.String getIpAddress() { return ipAddress_; }
    
    // required string host_name = 2;
    private boolean hasHostName;
    private java.lang.String hostName_ = "";
    public boolean hasHostName() { return hasHostName; }
    public java.lang.String getHostName() { return hostName_; }
    
    // required int64 port_number = 3;
    private boolean hasPortNumber;
    private long portNumber_ = 0L;
    public boolean hasPortNumber() { return hasPortNumber; }
    public long getPortNumber() { return portNumber_; }
    
    // required string licensed_ip_or_host = 4;
    private boolean hasLicensedIpOrHost;
    private java.lang.String licensedIpOrHost_ = "";
    public boolean hasLicensedIpOrHost() { return hasLicensedIpOrHost; }
    public java.lang.String getLicensedIpOrHost() { return licensedIpOrHost_; }
    
    // optional string license_user = 5;
    private boolean hasLicenseUser;
    private java.lang.String licenseUser_ = "";
    public boolean hasLicenseUser() { return hasLicenseUser; }
    public java.lang.String getLicenseUser() { return licenseUser_; }
    
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.newBuilder()
      private Builder() {}
      
      net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse result = new net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse();
      
      protected net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.getDescriptor();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse getDefaultInstanceForType() {
        return net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.getDefaultInstance();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse buildPartial() {
        net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string ip_address = 1;
      public boolean hasIpAddress() {
        return result.hasIpAddress();
      }
      public java.lang.String getIpAddress() {
        return result.getIpAddress();
      }
      public Builder setIpAddress(java.lang.String value) {
        result.hasIpAddress = true;
        result.ipAddress_ = value;
        return this;
      }
      public Builder clearIpAddress() {
        result.hasIpAddress = false;
        result.ipAddress_ = "";
        return this;
      }
      
      // required string host_name = 2;
      public boolean hasHostName() {
        return result.hasHostName();
      }
      public java.lang.String getHostName() {
        return result.getHostName();
      }
      public Builder setHostName(java.lang.String value) {
        result.hasHostName = true;
        result.hostName_ = value;
        return this;
      }
      public Builder clearHostName() {
        result.hasHostName = false;
        result.hostName_ = "";
        return this;
      }
      
      // required int64 port_number = 3;
      public boolean hasPortNumber() {
        return result.hasPortNumber();
      }
      public long getPortNumber() {
        return result.getPortNumber();
      }
      public Builder setPortNumber(long value) {
        result.hasPortNumber = true;
        result.portNumber_ = value;
        return this;
      }
      public Builder clearPortNumber() {
        result.hasPortNumber = false;
        result.portNumber_ = 0L;
        return this;
      }
      
      // required string licensed_ip_or_host = 4;
      public boolean hasLicensedIpOrHost() {
        return result.hasLicensedIpOrHost();
      }
      public java.lang.String getLicensedIpOrHost() {
        return result.getLicensedIpOrHost();
      }
      public Builder setLicensedIpOrHost(java.lang.String value) {
        result.hasLicensedIpOrHost = true;
        result.licensedIpOrHost_ = value;
        return this;
      }
      public Builder clearLicensedIpOrHost() {
        result.hasLicensedIpOrHost = false;
        result.licensedIpOrHost_ = "";
        return this;
      }
      
      // optional string license_user = 5;
      public boolean hasLicenseUser() {
        return result.hasLicenseUser();
      }
      public java.lang.String getLicenseUser() {
        return result.getLicenseUser();
      }
      public Builder setLicenseUser(java.lang.String value) {
        result.hasLicenseUser = true;
        result.licenseUser_ = value;
        return this;
      }
      public Builder clearLicenseUser() {
        result.hasLicenseUser = false;
        result.licenseUser_ = "";
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_ClusterMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_ClusterMessage_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_ClusterMessage_descriptor,
          new java.lang.String[] { "ServerUniqueId", "IsIndexReady", "IndexReady", "IsListRequest", "ListRequest", "IsListResponse", "ListResponse", "IsPingRequest", "PingRequest", "IsPingResponse", "PingResponse", },
          net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.ClusterMessage.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_IndexReady_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_IndexReady_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_IndexReady_descriptor,
          new java.lang.String[] { "Index", "MainTimestamp", "TempTimestamp", },
          net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.IndexReady.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_ListRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_ListRequest_descriptor,
          new java.lang.String[] { },
          net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.ListRequest.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_descriptor,
          new java.lang.String[] { "IndexStatus", },
          net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_IndexStatus_descriptor =
      internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_descriptor.getNestedTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_IndexStatus_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_ListResponse_IndexStatus_descriptor,
          new java.lang.String[] { "Index", "Timestamp", },
          net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.ListResponse.IndexStatus.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_PingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_PingRequest_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_PingRequest_descriptor,
          new java.lang.String[] { },
          net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.PingRequest.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_javacoding_xsearch_cluster_protocol_PingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_javacoding_xsearch_cluster_protocol_PingResponse_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_net_javacoding_xsearch_cluster_protocol_PingResponse_descriptor,
          new java.lang.String[] { "IpAddress", "HostName", "PortNumber", "LicensedIpOrHost", "LicenseUser", },
          net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.class,
          net.javacoding.xsearch.cluster.protocol.Cluster.PingResponse.Builder.class);
}
