--- TO BE RUN ONLY ONCE FOR INITIAL SYSTEM SETUP ---

--- INSERT SYSTEM LEVEL GUEST ACCESS AND ADMIN ACCESS ---
INSERT INTO AUTH_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, GUEST_FLG, ACTIVE, ACCESS_FEATURES, DEFAULT_ACCESS_FLG, ACCESS_ORDER, CREATED_BY, IS_AUTHORIZATION_REQUIRED)
VALUES ('GUEST_ACCESS', 'DEFAULT ACCESS TO THE SYSTEM', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'Y', '', 'Y', NULL, 'SYSTEM', 'N')

INSERT INTO AUTH_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, GUEST_FLG, ACTIVE, ACCESS_FEATURES, DEFAULT_ACCESS_FLG, ACCESS_ORDER, CREATED_BY, IS_AUTHORIZATION_REQUIRED)
VALUES ('ROAM_ADMIN', 'DEFAULT ADMIN ACCESS TO THE SYSTEM', GETDATE(), GETDATE(), 'SYSTEM', 'N', 'Y', '', 'N', NULL, 'SYSTEM', 'N')


--- INSERT ECOM ADMINISTRATION MODULE ACCESSES ---
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('C_USER','General User',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('C_USER_ADMIN','Enable User Actions',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_RECURRINGTX_ADMIN','View Recurring Transactions',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_WEBTX_ADMIN','View Web Transactions',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_OTCTX_ADMIN','View OTC Transactions',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_REFUNDTX_ADMIN','Enable Refunding Transaction',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_CHECKPRINT_ADMIN','Enable Check Printing',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
INSERT INTO AUTH_ADMIN_ACCESS (ACCESS_CD, ACCESS_DESCR, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES('C_CHECKHISTORY_ADMIN','View Check History',GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')


--- INSERT CODELOOKUP INFORMATION ---
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('WEEK','Every Week','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('BIWK','Every Two Weeks','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('SMMO','Twice Every Month','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('FRWK','Every Four Weeks','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('MONT','Every Month','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('QTER','Every Three Months','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('SMYR','Twice Every Year','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('YEAR','Every Year','Y',GETDATE(),GETDATE(),'ADMIN','RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('PP','Per Page - Fixed','Y',GETDATE(),GETDATE(),'ADMIN','NON_RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('PD','Per Document - Fixed','Y',GETDATE(),GETDATE(),'ADMIN','NON_RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('FREE','Free Access','Y',GETDATE(),GETDATE(),'ADMIN','FREE_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('PPV','Per Page - Variable','Y',GETDATE(),GETDATE(),'ADMIN','NON_RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP (CODE, DESCRIPTION, ACTIVE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, CATEGORY, CREATED_BY)
VALUES ('FR','Flat Rate - Flat','Y',GETDATE(),GETDATE(),'ADMIN','NON_RECURRING_SUBSCRIPTION', 'SYSTEM')
INSERT INTO CODELOOKUP(CODE, DESCRIPTION, CATEGORY, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('AICMS','Court Case Management System','REGISTERED_APPLICATION',GETDATE(), GETDATE(), 'ADMIN', 'Y', 'SYSTEM')
INSERT INTO CODELOOKUP(CODE, DESCRIPTION, CATEGORY, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('AILIS','Land Information System','REGISTERED_APPLICATION',GETDATE(), GETDATE(), 'ADMIN', 'Y', 'SYSTEM')
INSERT INTO CODELOOKUP(CODE, DESCRIPTION, CATEGORY, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('EUNIVERSA','EUniversa Efiling','REGISTERED_APPLICATION',GETDATE(), GETDATE(), 'ADMIN', 'Y', 'SYSTEM')
GO

-- INSERT SYSTEM LEVEL ADMIN USER
INSERT INTO AUTH_USERS (EMAIL_ID, PASSWORD, FIRST_NAME, LAST_NAME, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ADDRESS_1, ADDRESS_2, CITY, STATE, ZIP, PHONE, CREATED_IP, 
						ACCOUNT_NONEXPIRED, ACCOUNT_NONLOCKED, CREDENIALS_NONEXPIRED, ACTIVE, LAST_LOGIN_TIME, REGISTERED_NODE, CURRENT_LOGIN_TIME, CREATED_BY)
				VALUES ('admin@roam.com', '2851FFD2E30E91904A9E86F326E442065D75DB65A028854E9A5ACEE67E53EA59', 'ROAM', 'ADMIN', GETDATE(), GETDATE(), 'admin@roam.com', null, null, null, null, null, null, '1.1.1.1.1', 
						'Y', 'Y', 'Y', 'Y', GETDATE(), 'SUFFOLK', GETDATE(), 'SYSTEM')
DECLARE @ACCESS_ID AS INT = (SELECT TOP 1 ID FROM AUTH_ACCESS WHERE ACCESS_CD = 'ROAM_ADMIN')
DECLARE @USER_ID AS INT = (SELECT TOP 1 ID FROM AUTH_USERS WHERE EMAIL_ID = 'admin@roam.com')
INSERT INTO AUTH_USERS_ACCESS (ACCESS_ID, USER_ID, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, COMMENTS, IS_ACCESS_OVERRIDDEN, CREATED_BY, IS_AUTHORIZED)
				VALUES (@ACCESS_ID, @USER_ID, GETDATE(), GETDATE(), 'SYSTEM', 'Y', NULL, 'N', 'SYSTEM', 'Y')
				
--- INSERT TERM TYPE INFORMATION ---
INSERT INTO AUTH_TERM_TYP (TERM_TYP_CD, TERM_TYP_DESC, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY)
VALUES ('R', 'REGISTRATION', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM')
GO



------------*************************NODE SPECIFIC SCRIPTS *******************************************---------------
/* TO BE RUN FOR NEW NODE INSTALLATION - RECORDS MANAGEMENT */
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--- INSERT NODE INFORMATION ---
INSERT INTO ECOMM_NODE (NAME, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY, DESCRIPTION)
VALUES ('RECORDSMANAGEMENT', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM', 'Records Management')
GO

--- INSERT NODE CONFIGURATION INFORMATION ---
DECLARE @NODE_ID AS INT = (SELECT TOP 1 ID FROM ECOMM_NODE WHERE NAME = 'RECORDSMANAGEMENT')
INSERT INTO NODE_CONFIGURATION (NODE_ID, EMAIL_TEMPLATE_FOLDER, FROM_EMAIL_ADDRESS, RESET_PASSWORD_SUB, USER_ACTIVATION_SUB, 
	RESET_PASSWORD_TEMPLATE, USER_ACTIVATION_TEMPLATE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, LOCK_USER_TEMPLATE, 
	LOCK_USER_SUB, UNLOCK_USER_TEMPLATE, UNLOCK_USER_SUB, ALERT_SUBJECT, ALERT_TEMPLATE, CREATED_BY)
VALUES (@NODE_ID, 'Records Management/', 'noReply@amcad.com', 'Reset Password -  Roam Records Management', 
		'User Activation -  Roam Records Management', 'resetPassword.stl', 'resendActivation.stl', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 
		'lockuser.stl', 'User Account Locked - Roam Records Management', 'unlockuser.stl', 'User Account Unlocked -  Roam Records Management', 
		'Alert -  Roam Records Management', 'alert.stl', 'SYSTEM')
GO


------------*************************OTC Specific Scripts *******************************************---------------
/* TO BE RUN FOR NEW NODE INSTALLATION - OTC */
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--- INSERT NODE INFORMATION ---
INSERT INTO ECOMM_NODE (NAME, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY, DESCRIPTION)
VALUES ('OTC-NODE', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM', 'Over The Counter Transactions')
DECLARE @NODE_ID AS INT = (SELECT TOP 1 ID FROM ECOMM_NODE WHERE NAME = 'OTC-NODE')
GO



------------*************************NODE SPECIFIC SCRIPTS *******************************************---------------
/* TO BE RUN FOR NEW NODE INSTALLATION - CASE MANAGEMENT */
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--- INSERT NODE INFORMATION ---
INSERT INTO ECOMM_NODE (NAME, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY, DESCRIPTION)
VALUES ('CASEMANAGEMENT', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM', 'Case Management')
GO

--- INSERT NODE CONFIGURATION INFORMATION ---
DECLARE @NODE_ID AS INT = (SELECT TOP 1 ID FROM ECOMM_NODE WHERE NAME = 'CASEMANAGEMENT')
INSERT INTO NODE_CONFIGURATION (NODE_ID, EMAIL_TEMPLATE_FOLDER, FROM_EMAIL_ADDRESS, RESET_PASSWORD_SUB, USER_ACTIVATION_SUB, 
	RESET_PASSWORD_TEMPLATE, USER_ACTIVATION_TEMPLATE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, LOCK_USER_TEMPLATE, 
	LOCK_USER_SUB, UNLOCK_USER_TEMPLATE, UNLOCK_USER_SUB, ALERT_SUBJECT, ALERT_TEMPLATE, CREATED_BY)
VALUES (@NODE_ID, 'Case Management/', 'noReply@amcad.com', 'Reset Password -  Roam Case Management', 
		'User Activation -  Roam Case Management', 'resetPassword.stl', 'resendActivation.stl', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 
		'lockuser.stl', 'User Account Locked - Roam Case Management', 'unlockuser.stl', 'User Account Unlocked -  Roam Case Management', 
		'Alert -  Roam Case Management', 'alert.stl', 'SYSTEM')
GO


------------*************************NODE SPECIFIC SCRIPTS *******************************************---------------
/* TO BE RUN FOR NEW NODE INSTALLATION - WEB PAYMENTS */
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--- INSERT NODE INFORMATION ---
INSERT INTO ECOMM_NODE (NAME, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, CREATED_BY, DESCRIPTION)
VALUES ('WEBPAYMENTS', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 'SYSTEM', 'Web Payments')
GO

--- INSERT NODE CONFIGURATION INFORMATION ---
DECLARE @NODE_ID AS INT = (SELECT TOP 1 ID FROM ECOMM_NODE WHERE NAME = 'WEBPAYMENTS')
INSERT INTO NODE_CONFIGURATION (NODE_ID, EMAIL_TEMPLATE_FOLDER, FROM_EMAIL_ADDRESS, RESET_PASSWORD_SUB, USER_ACTIVATION_SUB, 
	RESET_PASSWORD_TEMPLATE, USER_ACTIVATION_TEMPLATE, DATE_TIME_CREATED, DATE_TIME_MOD, MOD_USER_ID, ACTIVE, LOCK_USER_TEMPLATE, 
	LOCK_USER_SUB, UNLOCK_USER_TEMPLATE, UNLOCK_USER_SUB, ALERT_SUBJECT, ALERT_TEMPLATE, CREATED_BY)
VALUES (@NODE_ID, 'Web Payments/', 'noReply@amcad.com', 'Reset Password -  Roam Web Payments', 
		'User Activation -  Roam Web Payments', 'resetPassword.stl', 'resendActivation.stl', GETDATE(), GETDATE(), 'SYSTEM', 'Y', 
		'lockuser.stl', 'User Account Locked - Roam Web Payments', 'unlockuser.stl', 'User Account Unlocked -  Roam Web Payments', 
		'Alert -  Roam Web Payments', 'alert.stl', 'SYSTEM')
GO