package com.fdt.security.entity.enums;

public enum AccessType {
    FREE_SUBSCRIPTION,
    RECURRING_SUBSCRIPTION,
    FIRM_DOC_BASED,
    FIRM_USER_BASED,
    NON_RECURRING_SUBSCRIPTION,
    CERTIFIED_NON_RECURRING_SUBSCRIPTION
}