/* Generated By:JavaCC: Do not edit this line. QueryAnalysisConstants.java */
package net.javacoding.xsearch.search.analysis;

public interface QueryAnalysisConstants {

  int EOF = 0;
  int WORD = 1;
  int INCHES = 2;
  int NUMBER = 3;
  int ACRONYM = 4;
  int SIGRAM = 5;
  int PLUS = 6;
  int MINUS = 7;
  int QUOTE = 8;
  int COLON = 9;
  int SLASH = 10;
  int DOT = 11;
  int SLOP = 12;
  int ATSIGN = 13;
  int APOSTROPHE = 14;
  int UNDERSCORE = 15;
  int AMPERSAND = 16;
  int STAR = 17;
  int QUESTIONMARK = 18;
  int WHITE = 19;
  int WORD_PUNCT = 20;
  int LETTER = 21;
  int CJK = 22;
  int DIGIT = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WORD>",
    "<INCHES>",
    "<NUMBER>",
    "<ACRONYM>",
    "<SIGRAM>",
    "\"+\"",
    "\"-\"",
    "\"\\\"\"",
    "\":\"",
    "\"/\"",
    "\".\"",
    "\"~\"",
    "\"@\"",
    "\"\\\'\"",
    "\"_\"",
    "\"&\"",
    "\"*\"",
    "\"?\"",
    "<WHITE>",
    "<WORD_PUNCT>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
  };

}
